<?php

namespace APIBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BoissonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoissonRepository extends EntityRepository
{
}
