<?php

namespace APIBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * uniteMesureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UniteMesureRepository extends EntityRepository
{
}
